image: $BUILD_SYSTEM

build:
  stage: build
  trigger:
    include: 
    #- local: .gitlab/stages/build.yml
    - 'https://github.com/$WORKING_ORG/StateOS_BA_GitLab/blob/dev/.gitlab/stages/test.yml'
    strategy: depend
    forward: 
      pipeline_variables: true

example_test:
  stage: test
  needs: ["build"]
  rules: 
    - if: $flag_example_test
  variables: 
    CURRENT_TEST: "example"
  trigger:
    include: 
    - local: .gitlab/stages/test.yml
    strategy: depend
    forward: 
      pipeline_variables: true

static_test:
  stage: test
  needs: ["build"]
  rules: 
    - if: $flag_static_test
  variables:
    CURRENT_TEST: "static"
  trigger:
    include: 
    #- 'https://github.com/MertensFlo/StateOS_BA_GitLab/blob/dev/.gitlab/stages/test.yml'
    - local: .gitlab/stages/test.yml
    strategy: depend
    forward: 
      pipeline_variables: true

unit_test:
  stage: test
  needs: ["build"]
  rules: 
    - if: $flag_unit_test
  variables:
    CURRENT_TEST: "unit"
  trigger:
    include: 
    - local: .gitlab/stages/test.yml
    strategy: depend
    forward: 
      pipeline_variables: true
