image: ubuntu:latest

variables:
  GLOBAL_VAR: "A global Variable"
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID


stages:
  - a
  - b
  - test

job_which_creates_something:
  stage: a
  script:
    - echo "MY_TEST_ENV=test_value" > my_artifacts.env
  artifacts:
    # this is to test if the environment variable inheritance works
    reports:
      dotenv: my_artifacts.env
    # this is to test if the file will show up or not, you probably don't need both
    paths:
      - my_artifacts.env


build:
  stage: b
  variables:
    LOCAL_VAR: "A local Variable"
  trigger:
    include: 
    - local: .gitlab/stages/build.yml
    forward: 
      pipeline_variables: true

test:
  stage: test
  trigger:
    include: 
    - local: .gitlab/stages/example_test.yml
    strategy: depend

static_test:
  trigger:
    include: 
    - local: .gitlab/stages/static_code_test.yml
    strategy: depend

unit_test:
  trigger:
    include: 
    - local: .gitlab/stages/unit_test.yml
    strategy: depend
