image: ubuntu:latest

stages:
  - a
  - b
  - test

build:
  stage: b
  variables:
    LOCAL_VAR: "A local Variable"
  trigger:
    include: 
    - local: .gitlab/stages/build.yml
    forward: 
      pipeline_variables: true

test:
  stage: test
  trigger:
    include: 
    - local: .gitlab/stages/example_test.yml
    strategy: depend

static_test:
  trigger:
    include: 
    - local: .gitlab/stages/static_code_test.yml
    strategy: depend

unit_test:
  trigger:
    include: 
    - local: .gitlab/stages/unit_test.yml
    strategy: depend
