image: $BUILD_SYSTEM

build:
  stage: build
  trigger:
    include: 
    - project: '$WORKING_ORG/$WORKING_REPO'
      ref: $WORKING_BRANCH
      file: '.gitlab/stages/build.yml'
    #- 'https://github.com/$WORKING_ORG/$WORKING_REPO/blob/$WORKING_BRANCH/.gitlab/stages/build.yml'
    strategy: depend
    forward: 
      pipeline_variables: true

example_test:
  stage: test
  #needs: ["build"]
  rules: 
    - if: $FLAG_EXAMPLE_TEST == true
  variables: 
    CURRENT_TEST: "example"
  trigger:
    include: 
    - project: '$WORKING_ORG/$WORKING_REPO'
      ref: $WORKING_BRANCH
      file: '.gitlab/stages/test.yml'
    strategy: depend
    forward: 
      pipeline_variables: true

static_test:
  stage: test
  needs: ["build"]
  rules: 
    - if: $FLAG_STATIC_TEST
  variables:
    CURRENT_TEST: "static"
  trigger:
    include: 
    - project: '$WORKING_ORG/$WORKING_REPO'
      ref: $WORKING_BRANCH
      file: '.gitlab/stages/test.yml'
    strategy: depend
    forward: 
      pipeline_variables: true

unit_test:
  stage: test
  needs: ["build"]
  rules: 
    - if: $FLAG_UNIT_TEST == true
  variables:
    CURRENT_TEST: "unit"
  trigger:
    include: 
    - project: '$WORKING_ORG/$WORKING_REPO'
      ref: $WORKING_BRANCH
      file: '.gitlab/stages/test.yml'
    strategy: depend
    forward: 
      pipeline_variables: true
